version: "3.8"

services:
  oracle:
    container_name: qs-oracle
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
      - "1522:1522"
    environment:
      - ORACLE_SID=xe
      - ORACLE_PWD=oracle

networks:
  default:
    external:
      name: quarkus-sampler-local-network
