version: "3.8"

# run from project directory
# docker-compose -f ./etc/docker-compose/docker-compose.local.observability.yml up --build --force-recreate
services:
    prometheus:
        container_name: prometheus
        volumes:
            - '../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
        image: prom/prometheus:v2.40.2
        ports:
            - '9090:9090'
    grafana:
        container_name: grafana
        volumes:
            - '../config/grafana/provisioning/:/etc/grafana/provisioning/'
        image: grafana/grafana:9.2.6
        ports:
            - '3000:3000'
    jaeger:
        container_name: jaeger
        image: jaegertracing/all-in-one
        volumes:
            - '../config/jaeger/sampling_strategies.json:/etc/jaeger/sampling_strategies.json'
        ports:
            - '6831:6831/udp'
            - '16686:16686'
networks:
    default:
        external:
            # if it could not be found on compose up, then execute: docker network create quarkus-sampler-local-network
            name: quarkus-sampler-local-network
