version: "3.8"

# run
# docker-compose -f <PROJECT_PATH>/quarkus-sampler/etc/docker-compose/docker-compose.local.qs-rest-service.yml up --build --force-recreate
#
# run from project directory
# docker-compose -f ./etc/docker-compose/docker-compose.local.qs-rest-service.yml up --build --force-recreate
#
# enter container
# docker exec -it qs-rest-service-dev /bin/bash
#
# empty run
# docker run --rm -it qs-rest-service:develop-local /bin/bash
services:
    qs-rest-service:
        container_name: qs-rest-service-dev
        build:
            context: ../../
            dockerfile: etc/docker-compose/local.fast-jar.Dockerfile
            args:
                ICELL_JAVA_17_JRE_BASE_IMAGE: 'icellmobilsoft/base-java17jre:1.4.0'
                SERVICE: 'qs-rest-service'
        image: "qs-rest-service:develop-local"
        environment:
            # With this config, service use application-dev.yml!
            - MP_CONFIG_PROFILE=dev
            - COFFEE_ETCD_DEFAULT_URL=http://qs-etcd:2379
            #- SAMPLER_LOGSTASH_MODULE_VERSION=1.0.0-SNAPSHOT
            #- SAMPLER_LOGSTASH_MODULE_ID=qs-rest-service-dev
            #- SAMPLER_LOGSTASH_K8S_NAMESPACE=test
            #- SAMPLER_LOGSTASH_ENABLED=true
            #- SAMPLER_LOGSTASTH_HOST=tcp:graylog
            #- SAMPLER_LOGSTASTH_PORT=12201
        ports:
            - '8080:8080' # REST
            - '5005:5005' # Debug
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 512M
networks:
    default:
        external:
            # if it could not be found on compose up, then execute: docker network create quarkus-sampler-local-network
            name: quarkus-sampler-local-network
