#-------------------------------
# Coffee config
#-------------------------------
coffee:
  app:
    name: ${quarkus.application.name}
  config:
    resource:
      bundles: i18n.common-messages,i18n.messages
    xml:
      catalog:
        path: xsd/hu/icellmobilsoft/quarkus/sampler/dto/super.catalog.xml

mp:
  openapi:
    filter: hu.icellmobilsoft.quarkus.sampler.rest.filter.OpenAPIFilter

#-------------------------------
# Quarkus settings
#-------------------------------
quarkus:
  arc:
    remove-unused-beans: false
  log:
    category:
      "hu.icellmobilsoft":
        level: ${SAMPLER_LOG_HU_ICELLMOBILSOFT_LEVEL:INFO}
    console:
      json: ${SAMPLER_LOG_CONSOLE_JSON_ENABLED:false}
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [thread:%t] [%c{10}] [sid:%X{extSessionId}] - %s%E%n"
    handler:
      gelf:
        additional-field:
          "moduleVersion":
            value: ${SAMPLER_LOGSTASH_MODULE_VERSION:unknown}
          "moduleId":
            value: ${SAMPLER_LOGSTASH_MODULE_ID:unknown}
          "K8S_NAMESPACE":
            value: ${SAMPLER_LOGSTASH_K8S_NAMESPACE:unknown}
        include-full-mdc: false
    level: ${SAMPLER_LOG_LEVEL:INFO}
    min-level: ${SAMPLER_LOG_MIN_LEVEL:ALL}
  jaeger:
    sampler-type: ${SAMPLER_JAEGER_SAMPLER_TYPE:remote}
    sampler-manager-host-port: ${SAMPLER_JAEGER_SAMPLER_MANAGER_HOST_PORT:localhost:5778}
    reporter-log-spans: ${SAMPLER_JAEGER_REPORTER_LOG_SPANS:true}
    sampler-param: ${SAMPLER_JAEGER_SAMPLER_PARAM:1}
    enabled: ${SAMPLER_JAEGER_ENABLED:false}
  rest-client:
    "hu.icellmobilsoft.quarkus.sampler.rest.restclient.ITestSecondQuarkusSamplerServiceRestRegisteredClient":
      url: http://localhost:8080
      scope: jakarta.enterprise.context.ApplicationScoped
      #read-timeout: 5000
      #connect-timeout: 5000
    "hu.icellmobilsoft.quarkus.sampler.rest.restclient.ITestQuarkusSamplerServiceRestRegisteredClient":
      url: http://localhost:8080
      scope: jakarta.enterprise.context.ApplicationScoped
      #read-timeout: 5000
      #connect-timeout: 5000
  package:
    add-runner-suffix: false
    type: uber-jar
  smallrye-openapi:
    info-title: Quarkus sampler service
    info-version: ${quarkus.application.version}
    info-description: >
      REST endpoints for operations. <br/> 
      General responses in case of error:  <br/> 
      * __400__ - Bad Request <br/> 
      * __401__ - Unauthorized <br/> 
      * __404__ - Not found <br/> 
      * __418__ - Database object not found <br/> 
      * __500__ - Internal Server Error <br/>
  swagger-ui:
    enable: false

